### ISSUE TITLE
React upgrade and cleanup - step I: Upgrade to latest version

### ISSUE THREAD

**Issue by burakalver** [4dn-dcic/fourfront#193]

**Comment by carlvitzthum** [comment]
Encode versions:
react: 0.12.2
react-bootstrap: 0.15.1
babel-preset-es2015: 6.6.0
babel-preset-react: 6.5.0

update the following: /develop/snovault/npm-shrinkwrap.json
/develop/snovault/package.json
/node_modules/react/<multiple files>

**Comment by carlvitzthum** [comment]
Steps so far: updated package.json (ncu -u) and deleted npm-shrinkwrap.json. In package.json, added the following:
"react": "^15.3.1",
"react-dom": "^15.3.1",
"react-bootstrap": "^0.30.3"
And deleted react-forms. 

Completely rebuilt dependencies, made a new shrinkwrap, and now am purging js files. All of this is being done on a new branch, react_upgrade. After getting a minimal working homepage (at least), I will start to put js files back in.

**Comment by carlvitzthum** [comment]
Here, I will keep a list of major react changes that must be done for the upgrade.

**Changes**
implement react-dom
get rid of CloneWithProps

**Comment by j1z0** [comment]
hey this is cool, I'm guessing the encode guys would be interested in the bullet points of what all was needed once your done, so we can send it on to them after you got it all sorted.

**Comment by carlvitzthum** [comment]
With newer versions of React, we know have the choice of using React.createClass (the traditional way) or ... extends React.Component (the new, ES6 way). A nice summary is here: https://toddmotto.com/react-create-class-versus-component/

For the time being, since we're on a tight schedule and already are using mixins (which are NOT supported with extends React.Component), I will stick with React.createClass. Maybe we should revisit this later.

**Comment by carlvitzthum** [comment]
Running into the setProps problem repeatedly, so I'm gonna jump to phase II - implement Redux, even though all the JS isn't yet put back in.
